### ISSUE TITLE
Lodash function error

### ISSUE THREAD

**Issue by jnettik** [AtenDesignGroup/generator-center-subtheme#10]
When trying to spin up a subtheme, I get the error:

``` 
$ yo center-subtheme
undefined
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: _.startCase is not a function
    at yeoman.generators.Base.extend.promptUser (/usr/local/lib/node_modules/generator-center-subtheme/app/index.js:19:20)
    at /usr/local/lib/node_modules/generator-center-subtheme/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

This is using node v4.0.0 and npm v2.14.2

**Comment by pixelwhip** [comment]
I'm guessing lodash should be a dependency rather than a devDependency.

**Comment by jnettik** [comment]
That seemed to fix it. Not sure if there's a review or testing needed, so I'll hold off on merging and closing.

**Comment by zrpnr** [comment]
Ran across the error `Error: Cannot find module 'lodash'`
Moving it from devDependencies to dependencies and running `npm install` fixed,
recommend merging this fix if it's ready @jnettik

**Comment by zrpnr** [comment]
bump :)
